/**
 * Keyboard Plate - Generated by KLE-NG
 *
 * Cutout type: cherry-mx-basic
 * Stabilizer type: mx-basic
 * Plate thickness: 1.5 mm
 * Generated: 2026-06-11
 *
 * This file uses the @jscad/modeling API (OpenJSCAD v2).
 * Open with: https://openjscad.xyz/
 */
const jscad = require('@jscad/modeling')
const { polygon, roundedRectangle } = jscad.primitives
const { rotateZ, translate } = jscad.transforms
const { extrudeLinear } = jscad.extrusions
const { subtract, union } = jscad.booleans

const THICKNESS = 1.5 // mm

// --- Plate outline ---
const outline = translate([178.899, -58.695, 0], roundedRectangle({ size: [382.482, 141.391], roundRadius: 1 }))

// --- Shared shapes ---
const switch_shape = roundedRectangle({ size: [14, 14], roundRadius: 0.5 })
const stab_pad = roundedRectangle({ size: [7, 15], roundRadius: 0.5 })

// --- Switch cutouts ---
const switch_0 = switch_shape  // "5,0" 1u
const switch_1 = translate([24.765, 0, 0], switch_shape)  // "5,1" 1u
const switch_2 = translate([43.815, 0, 0], switch_shape)  // "4,7" 1u
const switch_3 = translate([248.603, 0, 0], switch_shape)  // "5,10" 1u
const switch_4 = translate([267.653, 0, 0], switch_shape)  // "5,11" 1u
const switch_5 = translate([291.465, 0, 0], switch_shape)  // "5,12" 1u
const switch_6 = translate([310.515, 0, 0], switch_shape)  // "5,13" 1u
const switch_7 = translate([166.675, -14.546, 0], rotateZ(0.209, switch_shape))  // "5,6" 1u
const switch_8 = translate([185.308, -10.586, 0], rotateZ(0.209, switch_shape))  // "5,7" 1u
const switch_9 = translate([203.942, -6.625, 0], rotateZ(0.209, switch_shape))  // "5,8" 1u
const switch_10 = translate([222.576, -2.664, 0], rotateZ(0.209, switch_shape))  // "5,9" 1u
const switch_11 = translate([74.465, -3.502, 0], rotateZ(-0.209, switch_shape))  // "5,2" 1u
const switch_12 = translate([93.098, -7.463, 0], rotateZ(-0.209, switch_shape))  // "5,3" 1u
const switch_13 = translate([111.732, -11.423, 0], rotateZ(-0.209, switch_shape))  // "5,4" 1u
const switch_14 = translate([130.366, -15.384, 0], rotateZ(-0.209, switch_shape))  // "5,5" 1u
const switch_15 = translate([48.578, -21.907, 0], switch_shape)  // "4,2" 1u
const switch_16 = translate([247.65, -21.907, 0], switch_shape)  // "3,10" 1u
const switch_17 = translate([10.478, -24.765, 0], switch_shape)  // "3,0" 1u
const switch_18 = translate([29.528, -24.765, 0], switch_shape)  // "3,1" 1u
const switch_19 = translate([266.7, -24.765, 0], switch_shape)  // "3,11" 1u
const switch_20 = translate([295.275, -24.765, 0], switch_shape)  // "3,12" 2u
const switch_21 = translate([339.09, -24.765, 0], switch_shape)  // "3,14" 1u
const switch_22 = translate([358.14, -24.765, 0], switch_shape)  // "3,15" 1u
const switch_23 = translate([171.626, -37.838, 0], rotateZ(0.209, switch_shape))  // "3,6" 1u
const switch_24 = translate([190.259, -33.878, 0], rotateZ(0.209, switch_shape))  // "3,7" 1u
const switch_25 = translate([208.893, -29.917, 0], rotateZ(0.209, switch_shape))  // "3,8" 1u
const switch_26 = translate([227.527, -25.956, 0], rotateZ(0.209, switch_shape))  // "3,9" 1u
const switch_27 = translate([10.478, -43.815, 0], switch_shape)  // "2,0" 1.5u
const switch_28 = translate([34.29, -43.815, 0], switch_shape)  // "2,1" 1u
const switch_29 = translate([69.514, -26.794, 0], rotateZ(-0.209, switch_shape))  // "3,2" 1u
const switch_30 = translate([88.147, -30.755, 0], rotateZ(-0.209, switch_shape))  // "3,3" 1u
const switch_31 = translate([106.781, -34.715, 0], rotateZ(-0.209, switch_shape))  // "3,4" 1u
const switch_32 = translate([125.415, -38.676, 0], rotateZ(-0.209, switch_shape))  // "3,5" 1u
const switch_33 = translate([261.938, -43.815, 0], switch_shape)  // "2,11" 1u
const switch_34 = translate([280.988, -43.815, 0], switch_shape)  // "2,12" 1u
const switch_35 = translate([304.8, -43.815, 0], switch_shape)  // "2,13" 1.5u
const switch_36 = translate([339.09, -43.815, 0], switch_shape)  // "2,14" 1u
const switch_37 = translate([358.14, -43.815, 0], switch_shape)  // "2,15" 1u
const switch_38 = translate([166.269, -58.453, 0], rotateZ(0.209, switch_shape))  // "2,6" 1u
const switch_39 = translate([184.903, -54.492, 0], rotateZ(0.209, switch_shape))  // "2,7" 1u
const switch_40 = translate([203.537, -50.531, 0], rotateZ(0.209, switch_shape))  // "2,8" 1u
const switch_41 = translate([222.171, -46.57, 0], rotateZ(0.209, switch_shape))  // "2,9" 1u
const switch_42 = translate([240.804, -42.61, 0], rotateZ(0.209, switch_shape))  // "2,10" 1u
const switch_43 = translate([3.334, -62.865, 0], switch_shape)  // "1,0" 1.25u
const switch_44 = translate([34.29, -62.865, 0], switch_shape)  // "1,1" 1u
const switch_45 = translate([56.236, -43.447, 0], rotateZ(-0.209, switch_shape))  // "2,2" 1u
const switch_46 = translate([74.87, -47.408, 0], rotateZ(-0.209, switch_shape))  // "2,3" 1u
const switch_47 = translate([93.504, -51.369, 0], rotateZ(-0.209, switch_shape))  // "2,4" 1u
const switch_48 = translate([112.137, -55.33, 0], rotateZ(-0.209, switch_shape))  // "2,5" 1u
const switch_49 = translate([252.413, -62.865, 0], switch_shape)  // "1,10" 1u
const switch_50 = translate([271.463, -62.865, 0], switch_shape)  // "1,11" 1u
const switch_51 = translate([302.419, -62.865, 0], switch_shape)  // "1,13" 2.25u
const switch_52 = translate([339.09, -62.865, 0], switch_shape)  // "1,14" 1u
const switch_53 = translate([358.14, -62.865, 0], switch_shape)  // "1,15" 1u
const switch_54 = translate([174.889, -76.096, 0], rotateZ(0.209, switch_shape))  // "1,6" 1u
const switch_55 = translate([193.522, -72.135, 0], rotateZ(0.209, switch_shape))  // "1,7" 1u
const switch_56 = translate([212.156, -68.175, 0], rotateZ(0.209, switch_shape))  // "1,8" 1u
const switch_57 = translate([230.79, -64.214, 0], rotateZ(0.209, switch_shape))  // "1,9" 1u
const switch_58 = translate([8.096, -81.915, 0], switch_shape)  // "0,0" 2.25u
const switch_59 = translate([39.053, -81.915, 0], switch_shape)  // "0,1" 1u
const switch_60 = translate([56.934, -63.071, 0], rotateZ(-0.209, switch_shape))  // "1,2" 1u
const switch_61 = translate([75.568, -67.032, 0], rotateZ(-0.209, switch_shape))  // "1,3" 1u
const switch_62 = translate([94.201, -70.993, 0], rotateZ(-0.209, switch_shape))  // "1,4" 1u
const switch_63 = translate([112.835, -74.953, 0], rotateZ(-0.209, switch_shape))  // "1,5" 1u
const switch_64 = translate([261.938, -81.915, 0], switch_shape)  // "0,10" 1u
const switch_65 = translate([288.131, -81.915, 0], switch_shape)  // "0,12" 1.75u
const switch_66 = translate([319.088, -86.677, 0], switch_shape)  // "0,14" 1u
const switch_67 = translate([148.59, -96.202, 0], switch_shape)  // "0,16" 1u
const switch_68 = translate([183.508, -93.74, 0], rotateZ(0.209, switch_shape))  // "0,6" 1u
const switch_69 = translate([202.141, -89.779, 0], rotateZ(0.209, switch_shape))  // "0,7" 1u
const switch_70 = translate([220.775, -85.818, 0], rotateZ(0.209, switch_shape))  // "0,8" 1u
const switch_71 = translate([239.409, -81.857, 0], rotateZ(0.209, switch_shape))  // "0,9" 1u
const switch_72 = translate([0.952, -100.965, 0], switch_shape)  // "4,0" 1.5u
const switch_73 = translate([29.528, -100.965, 0], switch_shape)  // "4,1" 1.5u
const switch_74 = translate([62.29, -83.685, 0], rotateZ(-0.209, switch_shape))  // "0,2" 1u
const switch_75 = translate([80.924, -87.646, 0], rotateZ(-0.209, switch_shape))  // "0,3" 1u
const switch_76 = translate([99.557, -91.607, 0], rotateZ(-0.209, switch_shape))  // "0,4" 1u
const switch_77 = translate([118.191, -95.567, 0], rotateZ(-0.209, switch_shape))  // "0,5" 1u
const switch_78 = translate([267.653, -100.965, 0], switch_shape)  // "4,10" 1.5u
const switch_79 = translate([300.038, -105.727, 0], switch_shape)  // "4,12" 1u
const switch_80 = translate([319.088, -105.727, 0], switch_shape)  // "4,14" 1u
const switch_81 = translate([338.138, -105.727, 0], switch_shape)  // "4,15" 1u
const switch_82 = translate([194.456, -110.888, 0], rotateZ(0.209, switch_shape))  // "4,6" 2.75u
const switch_83 = translate([234.053, -102.472, 0], rotateZ(0.209, switch_shape))  // "4,8" 1.5u
const switch_84 = translate([62.988, -103.309, 0], rotateZ(-0.209, switch_shape))  // "4,3" 1.5u
const switch_85 = translate([95.597, -110.24, 0], rotateZ(-0.209, switch_shape))  // "4,4" 2u
const switch_86 = translate([123.547, -116.182, 0], rotateZ(-0.209, switch_shape))  // "4,5" 1u

// --- Stabilizer cutouts ---
const stab_20_a = translate([283.337, -26.265, 0], stab_pad)
const stab_20_b = translate([307.213, -26.265, 0], stab_pad)
const stab_20 = union(stab_20_a, stab_20_b)  // stabilizer for "3,12" (switch 20)
const stab_51_a = translate([290.481, -64.365, 0], stab_pad)
const stab_51_b = translate([314.357, -64.365, 0], stab_pad)
const stab_51 = union(stab_51_a, stab_51_b)  // stabilizer for "1,13" (switch 51)
const stab_58_a = translate([-3.842, -83.415, 0], stab_pad)
const stab_58_b = translate([20.034, -83.415, 0], stab_pad)
const stab_58 = union(stab_58_a, stab_58_b)  // stabilizer for "0,0" (switch 58)
const stab_82_a = translate([183.091, -114.837, 0], rotateZ(0.209, stab_pad))
const stab_82_b = translate([206.445, -109.873, 0], rotateZ(0.209, stab_pad))
const stab_82 = union(stab_82_a, stab_82_b)  // stabilizer for "4,6" (switch 82)
const stab_85_a = translate([83.608, -109.225, 0], rotateZ(-0.209, stab_pad))
const stab_85_b = translate([106.962, -114.189, 0], rotateZ(-0.209, stab_pad))
const stab_85 = union(stab_85_a, stab_85_b)  // stabilizer for "4,4" (switch 85)

// --- Assembly ---
const allCutouts = union(
  switch_0,
  switch_1,
  switch_2,
  switch_3,
  switch_4,
  switch_5,
  switch_6,
  switch_7,
  switch_8,
  switch_9,
  switch_10,
  switch_11,
  switch_12,
  switch_13,
  switch_14,
  switch_15,
  switch_16,
  switch_17,
  switch_18,
  switch_19,
  switch_20,
  stab_20,
  switch_21,
  switch_22,
  switch_23,
  switch_24,
  switch_25,
  switch_26,
  switch_27,
  switch_28,
  switch_29,
  switch_30,
  switch_31,
  switch_32,
  switch_33,
  switch_34,
  switch_35,
  switch_36,
  switch_37,
  switch_38,
  switch_39,
  switch_40,
  switch_41,
  switch_42,
  switch_43,
  switch_44,
  switch_45,
  switch_46,
  switch_47,
  switch_48,
  switch_49,
  switch_50,
  switch_51,
  stab_51,
  switch_52,
  switch_53,
  switch_54,
  switch_55,
  switch_56,
  switch_57,
  switch_58,
  stab_58,
  switch_59,
  switch_60,
  switch_61,
  switch_62,
  switch_63,
  switch_64,
  switch_65,
  switch_66,
  switch_67,
  switch_68,
  switch_69,
  switch_70,
  switch_71,
  switch_72,
  switch_73,
  switch_74,
  switch_75,
  switch_76,
  switch_77,
  switch_78,
  switch_79,
  switch_80,
  switch_81,
  switch_82,
  stab_82,
  switch_83,
  switch_84,
  switch_85,
  stab_85,
  switch_86
)
const plate2d = subtract(outline, allCutouts)
const plate3d = extrudeLinear({ height: THICKNESS }, plate2d)
const finalPlate = plate3d

const main = () => finalPlate

module.exports = { main }